"""remove test col

Revision ID: 3d500dede0ce
Revises: 47688a59e189
Create Date: 2013-03-26 17:58:29.590121

"""

# revision identifiers, used by Alembic.
revision = '3d500dede0ce'
down_revision = '47688a59e189'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', u'test')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(u'test', sa.VARCHAR(length=255), nullable=True))
    ### end Alembic commands ###
